### ISSUE TITLE
unv2oofem

### ISSUE THREAD

**Issue by houhouhou9998** [oofem/oofem#108]
hello,
I export an unv file form salome. Then, I want to use oofem as a solver to deal with this unv file, but I don't know how to create a control file which unv2oofem need. So, I wanna ask how to create my control file? Control file seems not to be created by unv2oofem automatically.

**Comment by bpatzak** [comment]
Hi,
there is a page on unvěoofem on oofem wiki: http://www.oofem.org/wiki/doku.php?id=unv2oofem:unv2oofem
The control file syntax follows closely the input file format, with no nodes and elements and some additional syntax allowing to map materials, boundary conditions etc to defined unv groups.

**Comment by houhouhou9998** [comment]
Thanks for your answer, and I am also curious if there are tools can create control file for every unv file automaticallly?

**Comment by bpatzak** [comment]
No, the control file contains the complementary information not present in unv. UNV contains only geometry and connectivity, ctrl file contains material properties, boundary conditions, etc.

**Comment by houhouhou9998** [comment]
Thanks, I get it.
