### ISSUE TITLE
Missing oofem_export.h include

### ISSUE THREAD

**Issue by mpalaversa** [oofem/oofem#154]
I have just tried to compile the latest code from the master on VS. I know that there have been issues with OOFEM_EXPORT on VS compilers and probably this file has been added to solve these problems, but when I pull the latest code, the file is not there and Visual Studio throws the error of the missing file in assemblercallback.h

**Comment by bpatzak** [comment]
This should be fixed already in devel branch, the pull request to master branch is waiting for approval.

**Comment by mpalaversa** [comment]
That's right. Confirmed! No problems building the last code from devel on VS.
