### ISSUE TITLE
Can oofem compiled with Python2?

### ISSUE THREAD

**Issue by xuhenry** [oofem/oofem#36]
Hello,
  Can oofem compiled with Python2?
Thanks a lot!
Henry

**Comment by vit-smilauer** [comment]
Hi Henry,
there is OOFEM's API for Python, currently supporting Python 3.x. However, there is only a few changes necessary in getting it working with Python 2.x. In oofemlib.cpp, change kw.items() to Python 2's kw.iteritems(). A few more fixes may be necessary in print() functions. Or download OOFEM's versions before Aug 30, 2018 where Python 2.x was the default.
Regards. Vit

**Comment by Micket** [comment]
I think we can close this ticket; especialyl considering python2's impending death.
