### ISSUE TITLE
Problem with using python bindings

### ISSUE THREAD

**Issue by laky55555** [oofem/oofem#37]
Hello,
I can't use python bindings after upgrading to python3 like I used them before.
With BOOST_LIB_VERSION 1.58 on ubuntu 16.04:
1. oofem compiled from commit 54997c0d840ce2a401a3689205e94d368c457cf8 (May, 4) works for python2 as expected
1. oofem complied from faf0606d912ef04c4248ee3d8d50d526973b4a40 (latest master) doesn't work for python3 as expected, when running test3.py from bindings/python everything is ok but on test2.py a lot of liboofem function doesn't work (e.g. liboofem.isoLE, liboofem.simpleCS, liboofem.loadTimeFunction, liboofem.peakFunction, ...) with error message _TypeError: No to_python (by-value) converter found for C++ type: std::unique_ptr<oofem::Function, std::default_delete<oofem::Function> >_

With BOOST_LIB_VERSION 1.65 on ubuntu 18.04:
1. oofem compiled from commit 54997c0d840ce2a401a3689205e94d368c457cf8 (May, 4) works just for loading from file (test3.py) but when running test2.py following error occurs 
```
Traceback (most recent call last):
  File "test2.py", line 10, in <module>
    problem = liboofem.linearStatic(nSteps=3, outFile="test2.out")
  File "<string>", line 2, in <module>
NameError: name 'kw' is not defined
```
2. oofem compiled from faf0606d912ef04c4248ee3d8d50d526973b4a40 (latest master) has the same problem as for python2. Works for test3.py type of problems but not for defining problem like in test2.py. Same error occurs. 

Do you maybe have working version (I would especially like python3 version) and if you do, which OS/libraries do you use. 

Thank you for your time,
Ivan

**Comment by bpatzak** [comment]
Hi, we have recently switched to use pybind11 to generate python bindings. The old boost based bindings are still there, but marked as obsolete).
The new solution fully supports Python3. You can check the python binding manual for more info and examples.

**Comment by laky55555** [comment]
That sounds great.
Thank you for your effort to keep the project up to date with latest trends.
Documentation around python is also very helpful and informative.
