### ISSUE TITLE
Set BC on elements?

### ISSUE THREAD

**Issue by cenxin995886** [oofem/oofem#44]
Hi,at present I am using oofem to do some simple tests.But I have a problem about  boundary conditions.
I wonder if I can only set the boundary condition (not boundary load) on  nodes in oofem.
If I could set boundary condition on elements.And how to set?
Now I'm use salome to create model and mesh generation.Then use unv2oofem.py.So if I want to set bc on elements how to write .ctrl file?Could you give me some advice or if you have some documents about it?
Thank you very much

**Comment by vit-smilauer** [comment]
Hi,
sure, you can assign prescribed values at nodes (displacements in mechanics, temperatures in heat problem etc.) as Dirichlet boundary conditions. Look in e.g. tests/sm/idm08.in. Setting Dirichlet boundary condition on an element makes no sense by the formulation of finite element method, it can be assigned to nodes only. Please, be more specific if you need further help.
Vit
