### ISSUE TITLE
Change element's material at a given time step

### ISSUE THREAD

**Issue by yanluding** [oofem/oofem#52]
Hi, 

Has anyone tried to change the element's material at given time steps? I know the programme can mark elements as active or inactive at a specific time step using _activityLTF_, but it seems the element's material has to keep the same after status change. Can I change the material while the elements are being activated? 

Thanks and regards,

Ding

**Comment by Micket** [comment]
This would be a big ask; changing the material state, to use a different material model, with different internal variables, would not only be a huge mess to try to achieve in the code, but also most likely not even well defined. In fact, the "activityLTF" is already borderline unrealistic.

If a material has to change behavior at some time, like solidifying/curing etc., it really needs to be a special material model that handles the switch internally.

In fact, there is a material that does this; `SimpleVitrificationMaterial`,.
