### ISSUE TITLE
oofeg compilation

### ISSUE THREAD

**Issue by githubgrasp** [oofem/oofem#56]
Is oofeg compilation still checked? Does not compile on Ubuntu with ggc-7.

**Comment by bpatzak** [comment]
Problem fixed. The updated version of Ckit is required (available from oofem download page).

**Comment by githubgrasp** [comment]
It compiles now if I switch off use_shared_lib 
If I leave this switch on, it fails during linking. Some error message related to Elixir:
Elixir/src/libelixir.a(elixir.o): relocation R_X86_64_PC32 against symbol `ElixirFindBestVisual' can not be used when making a shared object; recompile with -fPIC
