### ISSUE TITLE
Unused base class methods for lattice models

### ISSUE THREAD

**Issue by Micket** [oofem/oofem#63]
The lattice material models has 2 pairs of base class methods. One of them is defined in `LatticeStructuralMaterial`. These seem logical. 

But there are also methods in `StructuralMaterial`, named slightly different: `give3DLatticeStiffMtrx` and `give3dLatticeStiffMtrx`. Are these just leftovers? Could we please remove them?

@githubgrasp

**Comment by githubgrasp** [comment]
Yes, they should be removed. Feel free to do it. Or I will do it at the next pull request.

Peter

**Comment by githubgrasp** [comment]
I have done now the above changes. Much more had to be changed than expected.
Can you please check if the changes in structural element make sense.

Also, not everything is working yet. I created new IST entries for latticestrain and latticestress. However, the error checker in the lattice tests does not get the correct values when I use the numbers that correspond to the IST entries.

**Comment by Micket** [comment]
Fixed in PR #66
