### ISSUE TITLE
Missing includes during Windows compilation

### ISSUE THREAD

**Issue by johnnyontheweb** [oofem/oofem#81]
I continuosly find missing includes when compiling with Visual Studio.

Please find attached a patch for master branch, up to today.
[0001-Windows-compilation-patch-missing-includes.zip](https://github.com/oofem/oofem/files/4483330/0001-Windows-compilation-patch-missing-includes.zip)

**Comment by wcc201834748** [comment]
@johnnyontheweb sorry to bother you, i am a learner to oofem, i have some problems want to consult you but my english is not so well. I guess you are also a chinese, so may i add you email, qq or wechat to have a further suggestions. Thank you very much. Best regard.

**Comment by bpatzak** [comment]
Thank you, patch committed.
