### ISSUE TITLE
Nodal Stress

### ISSUE THREAD

**Issue by nitelm** [oofem/oofem#84]
Hi everyone, is there a way to compute and report average nodal stresses in OOFEM? 

If not, I would like to go ahead and implement it. Could you please let me know what you think about this?

**Comment by wcc201834748** [comment]
@nitelm sorry to bother you, i am a learner to oofem, i have some problems want to consult you but my english is not so well. I guess you are also a chinese, so may i add you email, qq or wechat to have a further suggestions. Thank you very much. Best regard.
